# 将静态内容部署到 GitHub Pages 的简易工作流程
name: Deploy docs to Pages

on:
  
  push:
    branches:
      - main
  
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i pnpm -g
      - run: pnpm install

      - name: Build Suiue
        run: pnpm run build:suiue

      - name: Build DOCS
        run: pnpm run build:docs
      - run: mv packages/docs/.vitepress/dist ./dist

      - name: Build DEMO
        run: pnpm run build:demo
      - run: mv packages/demo/dist ./dist/demo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist

