# 将静态内容部署到 GitHub Pages 的简易工作流程
name: Deploy docs to Pages

on:
  
  push:
    branches:
      - main
  
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i pnpm -g
      - run: pnpm install

      - name: Build DOCS
        run: pnpm build:docs ./dist
      - run: mv pacakages/docs/dist ./dist

      - name: Build DEMO
        run: pnpm build:demo
      - run: mv pacakges/demo/dist ./dist/demo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

